model_type: "residual_policy"

model_path: ""

policy_setup: "panda-ee-dpos"
obs_dim: 42
action_dim: 4
num_action_chunks: 8
hidden_dim: 256

precision: "32"
add_value_head: False
add_q_head: True
q_head_type: "default"  # ["default", "crossq"]

# Residual policy specific
actor_input: "obs"  # ["obs", "obs_base_action"] - Will be overridden by network.actor_input

is_lora: False
lora_rank: 32

